listeners:
- query_port: 25577
  motd: |2-
                        &e&lBlocksMC&r
                  &f&lConnection Optimizer
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: blocksmc
  ping_passthrough: false
  priorities:
  - blocksmc
  bind_local_address: false
  host: 0.0.0.0:25577
  max_players: 1337
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 512
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 10a1000c-b70c-4376-8d05-42ac2c3c25a9
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: -1
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  blocksmc:
    motd: '&1Just another Waterfall - Forced Host'
    address: play.blocksmc.com
    restricted: false
